version: "3.1"

services:
  mysql:
    build: docker/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33333:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "fnd_database"
    volumes:
      - ./docker/mysql_data:/var/lib/mysql
    restart: always
    networks:
      fnd_network:

  webserver:
    image: nginx:alpine
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - "8181:80"
    networks:
      fnd_network:

  php-fpm:
    build: docker/php-fpm
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
    networks:
      fnd_network:

networks:
  fnd_network:
    driver: bridge